sudo: required
language: python
services:
  - docker
arch:
  - arm64

before_script:
  - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASS}" "https://registry.weslyg.ru"

script:
  - docker build -t registry.weslyg.ru/auction:latest -f "Dockerfile.server" .
  - docker tag registry.weslyg.ru/auction:latest registry.weslyg.ru/auction:"${TRAVIS_BUILD_NUMBER}"
  - docker push registry.weslyg.ru/auction:latest
  - docker push registry.weslyg.ru/auction:"${TRAVIS_BUILD_NUMBER}"

after_script:
  - docker logout https://registry.weslyg.ru
